### ISSUE TITLE
Test GeoNode B/R

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-afghanistan#1]
The task here is to test the backup and restore management commands and configurations from master GeoNode with the following specific goals:

1. check if both backup and resotre commands work without errors
4. confirm the expected configurations (for GeoNode and Geoserver) and data (Geoserver stores) are correctly replicated

The following two points are particularly critical:

- verify if [.ini configurations](https://github.com/GeoNode/geonode/blob/master/geonode/base/management/commands/settings.ini#L17) for GeoNode fixtures are up to date 
- verify that GeoNode B/R REST API calls are working fine and with the correct results (Geoserver configurations are replicated)

Take notes of any problem and improvements. They will be used to define the next tasks, which include:

- move the commands and its helpers to a new dedicated "br" module
- move or remove the current  backup Django model and admin form
- pack the backup outputs into a single .zip file with an accomanying MD5 hash file
- implement descriptive configuration options to select what should be repliacted (users, permissions, layers, documents, maps, messages, etc.)
- implement a REST API around the b/r commands
- (...)

**Comment by bieganowski** [comment]
Testing of Geonode python3.6 version with Geoserver 2.16.2 report:

**MAJOR:**
1. Reload: MISSING replacement of some already defined models. Loading backup fixture on the non-empty database, causes e.g.:
![image](https://user-images.githubusercontent.com/57660086/75560471-817e4200-5a45-11ea-9780-2f6411119f64.png)
2. Geonode loading layer to PostGIS datastore: pygdal 2.2.3.3 has an issue with python 3. Pygdal upgrade to 2.2.3.6 is needed for proper execution.
3. Geonode declares UploadSession model below Layer model (in the `models.py` file), even though Layer has a foreign pointing at UploadSession. This causes behavior when Layer fixture is loaded first, and UploadSession it points at is not in the database.

**MINOR**
1. for Geoserver in docker (https://github.com/GeoNode/geoserver-docker) with volume: Geoserver's backup is created with `root` ownership, disabling the Geonode's from accessing it (reading, moving, zipping, etc).
5. for Geoserver in docker: Geonode tells Geoserver to create a dump in the directory that does not exist in the docker image. `geoserver_backup_dir` has to be manually changed to point at a volume, matching docker image path.
5. Reload: issue shown `NoticeType.DoesNotExist`. It doesn't cause error, though should be investigated, if backup of this application is needed.

**Comment by giohappy** [comment]
thanks @bieganowski.
Please @afabiani go through the notes then we should have a call quickly to define the steps.

The principal point is the replacement of already existing resources. The current b/r assumes to restore on an empty target instance, while our primary use case with disasterrisk is replacing a resource with an updated one.

Related to this is the restore of the pg dump. Probably the --clean option pf pg_restore is enough to wipe preexisting data before restoring a table.
@bieganowski can you test this option please?

**Comment by bieganowski** [comment]
@giohappy the `python manage.py restore` does not recognize `--clean` option as supported one.
Because this is what you wanted to test, right?

**Comment by giohappy** [comment]
I mean to test it oustide of the management command. In case it works as expected we could integrate it as a first step toward "replacement restore".

**Comment by giohappy** [comment]
Forget my comment about --clean option. It's already used: https://github.com/GeoNode/geonode/blob/master/geonode/base/management/commands/helpers.py#L247

**Comment by giohappy** [comment]
@bieganowski loaddata should overwrite already existing data. It's also described [here](https://docs.djangoproject.com/en/3.0/howto/initial-data/#providing-data-with-fixtures):

> Each time you run loaddata, the data will be read from the fixture and re-loaded into the database. Note this means that if you change one of the rows created by a fixture and then run loaddata again, you’ll wipe out any changes you’ve made.

We should inspect the errors we're getting about MultipleObjectsReturned, since they shouldn't happen.

**Comment by giohappy** [comment]
UPDATE:
- Patch to b/r command pushed and under review on GeoNode master: https://github.com/GeoNode/geonode/pull/5816
- Issue opened for the problem with restore in Geoserver 2.16.x: https://osgeo-org.atlassian.net/browse/GEOS-9530

**Comment by giohappy** [comment]
@bieganowski your fixes to b/r have been ported to 2.10.x (https://github.com/GeoNode/geonode/pull/5826).

Now it's time to test again the b/r using GN 2.10.x and Geoserver 2.15.3
