### ISSUE TITLE
Issues with patched Geoserver B/R libs

### ISSUE THREAD

**Issue by bieganowski** [geosolutions-it/geonode-afghanistan#15]
**Fixes needed for Backup/restore procedures:**

1. Two Geoserver libraries need to be updated: `gs-backup-restore-core` and `gs-backup-restore-rest` (valid for both: `2.15.3` and `2.16.2` GS versions)

2. After loading the updated libs, backup/restore HTTP requests need to be updated with the following headers:
```
headers = {
    'Accept': 'application/json',
    'Content-type': 'application/json'
}
```

3. After loading the updated libs, some communication (all?) with Geoserver fails. The known error occurred on a layer loading, while creating an `import session`. Geoserver started an import but it was infinite `PENDING` and manual import didn't cause any action. Observed with **Geoserver 2.16.2** and **GeoNode 2.10.x.** and PostgreSQL datastore. (_Issue not present with GeoNode 3_).
Most likely the requests are missing headers as in case of backup/restore procedure. Communication should be investigated and fixed ![image_2020_03_27T10_25_13_537Z.png](https://images.zenhubusercontent.com/5dcaa0a4967c490001dec827/3f5feb9c-d987-42d8-8e42-28c87cb4b6b3)
on the Geoserver side an exception was logged with a weird character within the brackets (which couldn't be not copied here):
```
2020-03-27 11:02:29,228 TRACE [importer.format] - Error reading file as json
java.lang.RuntimeException: Unexpected character () at position 0.
```

**Comment by giohappy** [comment]
We will wait for the PR from Michal regarding the patched b/r headers then @afabiani please proceed quickly with the issue described at point 3.

**Comment by giohappy** [comment]
@afabiani we won't create custom builds for GeoNode. I will submit the requests to build two new intermeditate minor releases for Geoserver (probably named 2.15.5.1 and 2.16.2.1) with the patches to the b/r libs.

**Comment by afabiani** [comment]
@giohappy @bieganowski updated GeoServer WARs can be found here

https://build.geo-solutions.it/geonode/geoserver/latest/

I built GeoServer 2.15.5 too if needed.

**WARNING**: I haven't updated any docker image yet

Tested locally:

* GeoServer 2.15.4
* GeoServer 2.15.5
* GeoServer 2.16.2

All of them work fine, backup & restore work (only tested from GeoServer GUI) fine and uploads from both GeoNode 2.10.x and 3.0 also work fine on my side.

**Comment by giohappy** [comment]
Builds for geonode/geoserver:2.16.2 and geonode/geoserver:2.15.4 are ready
