### ISSUE TITLE
Create a clone of the instance

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-afghanistan#16]
We need to clone the current instance and expose it with a public URL.

FYI the clone will serve the following purposes:
- upgrade the instance to GN 2.10.x and upgrade Geoserver to incorporate the fixes to the b/r module
- after that clone the instance again to test b/r between the two GN instances

**Comment by randomorder** [comment]
I checked the available resources on the server, we are good to go, only two questions:
- We need to schedule a temporary shut down of the VM with world bank (Cristiano Giovando). Can I go ahead and get in touch with him about this? (are we ok to clone the VM ASAP from your point of view?)
- Any preference for the DNS record of the new machine?

**Comment by giohappy** [comment]
ok @randomorder go ahead and tell Cristiano.
for the DNS could we have stage1.disasterrisk.af and stage2.disasterrisk.af? (the latter for the new clone we will do after the upgrade)

**Comment by randomorder** [comment]
https://stage1.disasterrisk.af/

Doc [here](https://docs.google.com/document/d/1i_85WBO41TXk5D1RuIxnncrIQbGV5RvXxcWPAZGc26M/edit#)

**Comment by randomorder** [comment]
When the time comes for the second clone, can you please create a dedicated issue?

**Comment by giohappy** [comment]
sure @randomorder
