### ISSUE TITLE
disasterrisk.af and assess-risk.info domains renewal

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode-afghanistan#17]
I would migrate these over to a well-known registrar if possible @simboss. Gandi DNS servers have not been very reliable lately..

Expire dates here below:
![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/00742feb-b66a-42e3-8490-b192355225d0)

**Comment by simboss** [comment]
@randomorder the problem is to find someone who can register an .af domain.

- Aruba does not
- Ovh seems to be able to transfer it

So please, schedule this activity with Giacomo so we get rid of Gandi. We should let people around this project know when we move this.

**Comment by randomorder** [comment]
@giacomoc92 
I'll get the ball rolling with the people involved and propose to do this early next week.
Before the end of this week make sure you have a clear understanding and all the information you need to perform the task

**Comment by giacomoc92** [comment]
@randomorder @simboss 
I have started the transfer procedure from ovh. Status can be seen from the 'orders' section of the ovh control panel https://www.ovh.com/manager/dedicated/#/billing/orders

**Comment by giacomoc92** [comment]
The transfer procedure for assess-risk.info has started, this is the current status:
![Screenshot from 2020-04-17 11-53-24](https://user-images.githubusercontent.com/49372260/79556978-14c91080-80a2-11ea-9f72-b2062f643adb.png)

Here are the dns records to restore
[assess-risk.info.txt](https://github.com/geosolutions-it/geonode-afghanistan/files/4492154/assess-risk.info.txt)

**Comment by randomorder** [comment]
What about https://disasterrisk.af/ @giacomoc92 ?

**Comment by giacomoc92** [comment]
We still need to pay for it

**Comment by randomorder** [comment]
Who? Simone? Is he aware of this? Link to the order to complete the payment?
It's Friday today @giacomoc92, we started this on Monday..

**Comment by giacomoc92** [comment]
I have received an email from "coccaregistry" informing me that disasterrisk.af is completed. From the ovh side it seems to be completed as well.

dns for disasterrisk
[disasterris.af.txt](https://github.com/geosolutions-it/geonode-afghanistan/files/4493049/disasterris.af.txt)

**Comment by randomorder** [comment]
remember to configure the DNS records in OVH before the current records expire and the server becomes unreachable

**Comment by giacomoc92** [comment]
DNS records on OVH for disasterrisk.af are updated, change is still propagating.

The status for assess-risk is still "Transfer request sent to registry, now waiting answer"

**Comment by randomorder** [comment]
What's the plan @giacomoc92 ?

**Comment by giacomoc92** [comment]
Looking at the status, they are waiting for confirmation by the current provider. Looking at [this](https://www.ovh.it/domini/procedura_trasferimento_dominio.xml?xtor=SEC-13-GOO-[it_int_2020_ovh_web_softc_awareness_reach_srch_offensivelouddeals2020_sale_acquisition_srch_offensive()]-[424850983675]-S-[]&xts=563736&sitelink=&gclid=CjwKCAjwkPX0BRBKEiwA7THxiJdGfjEwvY48GPbmCKia3ntyOQ5hfy5OXPzGd7iz346IxOt1cr6OGBoC084QAvD_BwE), it can take up to five days. I don't know if we can speed up this somehow.

**Comment by randomorder** [comment]
Have we acknowledged the tranfer via email?

**Comment by giacomoc92** [comment]
![Screenshot from 2020-04-21 17-39-05](https://user-images.githubusercontent.com/49372260/79885368-1161bc00-83f7-11ea-8fa8-942048c86bcc.png)
The tracking isn't moving. Actually, they are moving the estimated transfer date forward

The mails I recovered from Chiara were about assess-risk, I will check again with Chiara tomorrow, as she seems to be offline.

**Comment by giacomoc92** [comment]
I'll try getting in touch with Gandi

**Comment by giacomoc92** [comment]
assess-risk.info is completed too

**Comment by randomorder** [comment]
@giacomoc92 
Closing the issue. Please report to Cristiano Giovando is you haven't already and make sure the monitoring is enabled for both these services

**Comment by giacomoc92** [comment]
I have informed Cristiano.

>  and make sure the monitoring is enabled for both these services

Monitoring is enabled for disasterrisk.af and there are no entries for assess-risk.info. Is this correct?

**Comment by randomorder** [comment]
I don't know. You tell me :)

**Comment by simboss** [comment]
@giacomoc92 enable monitoring also on assess-risk
