### ISSUE TITLE
Test B/R between production and stage1

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-afghanistan#19]
Use production as the source and stage1 as the target to avoid any incident on the production instance data!

**Comment by afabiani** [comment]
B/R works fine now also with a full 12Gb backup file. We still need some improvements in order to lower down the size of the backup file as per https://github.com/geosolutions-it/geonode-afghanistan/issues/20

**Comment by giohappy** [comment]
@afabiani I suppose you fixed this by making Geoserver avoid adding the data folder from the config dump in Geoserver, right?
You can proceed with #20 as agreed.
