### ISSUE TITLE
Filter files from GeoNode uploaded/ folder

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-afghanistan#22]
Backup and Restore supports [filters](https://docs.geonode.org/en/master/intermediate/backup/index.html#settings-geoserver-section) to avoid dumping the Geoserver data for certain layers.
The effect is that data from Geoserver files and/or Postgres tables are nor dumped if they match filters.
**However the uploaded data in GeoNode are still dumped**

The task is to 

- [ ] move the filters configurations in a new dedicated [filters] section inside the .ini file (see below)
- [ ] update the Config class to keep the same current references for the alrady existing code (see below)
- [ ] implement the filtering of data from GeoNode's "uploaded/" folder according to the filter settings
- [ ] update the [documentation file](https://github.com/GeoNode/documentation/blob/master/intermediate/backup/index.rst)

### New "filters" section
```
[database]
pgdump = pg_dump
pgrestore = pg_restore

[filters]
# data_dt_filter = {cmp_operator} {ISO8601} e.g. > 2019-04-05T24:00
# data_layername_filter = {comma separated list of layernames, optionally with glob syntax} e.g.: tuscany_*,
# data_layername_exclude_filter = {comma separated list of layernames, optionally with glob syntax} e.g.: tuscany_*,italy

[geoserver]
datadir = geoserver/data
# datadir_exclude_file_path = {comma separated list of paths to exclude from geoserver catalog} e.g.: /data,/data/geonode,/geonode
dumpvectordata = yes
dumprasterdata = yes
```

### Keep the references inside Config class for existing code
E.g., from here:
```
if options.get("gs_data_dir", None):
        self.gs_data_dir = options.get("gs_data_dir")
        if self.config_parser:
            self.config_parser['geoserver']['datadir'] = self.gs_data_dir
```

to this:
```
if options.get("gs_data_dir", None):
        self.gs_data_dir = options.get("gs_data_dir")
        if self.config_parser:
            self.config_parser['filters']['datadir'] = self.gs_data_dir
```

**Comment by simboss** [comment]
@afabiani if you are not already working on this, please, leave it open.

**Comment by giohappy** [comment]
@abulojoshua1 as seen together the filters actually already exist for the media folder (and consequently the uploaded/ folder).

For the moment **skip the points in the original description** of this issue and just focus on understanding why the filters are not upplied correctly to the uploaded/ folder contents.

**Comment by giohappy** [comment]
please @abulojoshua1 report here the fix you made on GeoNode

**Comment by abulojoshua1** [comment]
So far, I have raised [this pull request](https://github.com/GeoNode/geonode/pull/6194) fixing issue [#6193](https://github.com/GeoNode/geonode/issues/6193) in Geonode. Whenever a directory with files at its root needs to be backed-up, it skips the `data_dt_filter` settings filter which makes it get backed up irrespective of filter values.

**Comment by giohappy** [comment]
@afabiani please test the fixed b/r on Afghanistan.
I remind you that the expected effect is that data files must not be dumped with GeoNode's uploaded/ folder

**Comment by afabiani** [comment]
Done

![image](https://user-images.githubusercontent.com/1278021/86761500-4bca1500-c046-11ea-8c70-a59084664b23.png)
